app/views/components/index.html, app/views/patterns/index.html
Replaced with recommended and experimental.
Restructured the components and patterns pages to use a table sorted first by recommended or experimental, then by name.
=> Replace Disco/Alpha/Beta/Live. 

app/views/includes/css/confirm.css
Changed the hex code for the confirmation panel background colour from #00823B to #006435 to match the visual example.
=> Correcting hex code in CSS example

app/views/includes/components/pagination.html, app/views/includes/home-office-logo.html
Removed emdash in pagination html and removed underscore in home office logo htmk due to accessibility errors.
Also removed the secondary link override in the gov frontend node as this was causing colour contrast errors. Not sure if this has committed
=> Accessibility changes

app/views/components/back.html, app/views/components/confirm-pages.html
Have removed links and references to the icons page (removed in previous branch) in the following Component pages:
- back link
- confirmation pages
=> references to icons removed

app/views/includes/components/conf--casework.html
This commit removes an apostrophe that shouldn't be there.
> Hi folks: there's a typo in the "Request received" example. "...and its current status" should *not* have an apostrophe in "it's".
> 
> ![image](https://user-images.githubusercontent.com/26182217/71012982-db7a9700-20e7-11ea-87da-557e684aca37.png)
> 
> _Originally posted by @martinwake in https://github.com/UKHomeOffice/design-system/issues/90#issuecomment-566623818_
>
=> Fix errant apostrophe

app/assets/sass/system/_subnav.scss, app/views/includes/left-pane__components.html, app/views/includes/left-pane__contribute.html, app/views/includes/left-pane__patterns.html, app/views/includes/left-pane__resources.html, app/views/includes/left-pane__styles-bu.html, app/views/includes/left-pane__styles.html, app/views/includes/top_nav.html
Hi
- Amended the colour contrast with the theme headings in the subnav
- Added aria-labels for all the sidenav components (style, component, pattern etc.) and global header for screen readers 
- I've decided not to change the focus state from your recommendation @kitation, for now that is, as I think just upping the boldness of the yellow might be a band aid fix, where the underlying problem might lie in the focus state itself (it being a border-color change rather than background-color change like gov.uk). This is something I will raise with the team and come up with some actions.
=> Sidenav fix

app/assets/sass/components/_buttons.scss, app/views/includes/components/button-primary-alt.html, app/views/includes/components/buttons-secondary.html, app/views/includes/components/buttons.html, app/views/includes/components/highlighting.html, app/views/includes/components/table-multiselect.html, app/views/patterns/make-an-enquiry.html
What's been done:
**Make an enquiry**
-  Example form now has labels attached to the field inputs
**Buttons**
- All buttons are now using <button> mark-up
**Highlight search results**
- Discussion with Yacoob and Atlas designers has led to the recommendation that including the highlighted words for screen readers might be more of a hindrance than a benefit. For now, they serve as a visual aid in some circumstances. Guidance will be added to the component to suggest the implementation of them are considered very carefully depending on the context of the service.
**Table-multi select**
- Checkboxes now have labels 
- The screen reader will now read out "clicked" and "un-clicked"
=> Accessibility issues corrected

app/views/styles/colour.html
Sentence removed as it was contradictory and could cause confusion:
> These combinations are used in the Home Office design system. They should only be used for graphics and visualisation.
=> Content removed

app/views/styles/colour.html
Current colour palette  is confusing:
1. duplicates GOV.UK colours in some areas
2. uses DDaT branding colours but not accessible with grey background 
This branch will highlight HO colours not used in GOV.UK and refer to GOV.UK as extended palette.
=> Updated and simplified colour page

apps/docs/src/common/pages/components.tsx
Replaces a reference to NotGovUK (with HODS) in a page description.
=> docs: Replace reference to NotGovUK

lib/create/Makefile
This will mean we don't need to type the extra data into the terminal.
=> create: Update to latest PLOP command

apps/docs/src/common/pages/contribute.tsx, apps/docs/src/common/pages/contribute/discuss-on-github.tsx, apps/docs/src/common/pages/get-started.tsx, apps/docs/src/common/pages/index.tsx
Changes 'github' to 'GitHub' for consistency.
Fixes 'compontent' to 'component'.
=> Fix mistakes in contribute guidance

components/time/src/utils.ts
We don't always have the en_GB locale available and end up with en_US.
This results in AM and PM being capitalised. We should force lower-case
to handle this scenario.
=> Time: Force lowercase to handle missing locale

lib/create/plopfile.js
extendGenerator is now an async function so we must await the result.
=> create: Fix call to extendGenerator

components/date-display/spec/DateDisplay.stories.mdx, components/date-display/spec/DateDisplay.ts, components/date-display/src/DateDisplay.tsx, components/date-time/src/DateTime.tsx, components/time/spec/Time.stories.mdx, components/time/spec/Time.ts, components/time/src/Time.tsx
Reverses the meaning of the `wrap` props on the new DateDisplay and Time components. This is because React has some nice syntax for handling flags.
Also removes public documentation for these props as they are mainly of use to ourselves in the DateTime component.
=> Flip wrap props to noWrap

apps/docs/src/common/pages/accessibility/forms.tsx
Added additional clarification to the forms guidance to point out the need to use autocomplete on input fields that collect user information.
=> Added autocomplete info to forms guidance

components/pagination/assets/Pagination.scss, components/pagination/package.json, components/pagination/spec/Navigation.ts, components/pagination/spec/Pagination.stories.mdx, components/pagination/spec/Pagination.ts, components/pagination/src/Navigation.tsx, components/pagination/src/Pagination.tsx, pnpm-lock.yaml
Fixes a bug in which the query parameters of the current page were lost
when clicking the links.
Moves the original 'navigation' into its own sub-component.
Simplifies the tests.
**BREAKING:** Simplifies the interface, children now _must_ be provided.
=> Pagination: Refactor and simplify interface

components/status-message/spec/StatusMessage.stories.mdx
This change simply removes the line on the status message component about needing to add a writing for this component section.
This was missed when approving and deploying https://github.com/UKHomeOffice/design-system/pull/463 - writing for status messages.
=> Remove writing from help improve this component

components/time/src/utils.ts
Generalised to remove all whitespace from time, rather than just spaces. This is because in newer version of node the whitespace between the time and am or pm has changed from a space (Unicode 32) to a narrow no-break space (Unicode 8239). Fixes issue https://github.com/UKHomeOffice/design-system/issues/492.
=> Remove all whitespace from time

apps/docs/src/common/pages/content-style-guide.tsx
Notification
Avoid using ‘notification’ or ‘notify’. Try to be specific about contact, such as, ‘we will send you an email’ or ‘how do you want to be contacted?’
Online status
Avoid using ‘online status’ or 'digital status' when referring to someone’s immigration status. Use ‘online immigration status’ instead.
Digital status
Avoid using ‘online status’ or 'digital status' when referring to someone’s immigration status. Use ‘online immigration status’ instead.
I've been changing the single speech marks (') to display consistently
=> New entries + punctuation edits

apps/docs/src/common/pages/patterns/enter-passport-details.tsx, apps/docs/src/common/pages/patterns/enter-passport-details/manually-enter-details.tsx, apps/docs/src/common/pages/patterns/enter-passport-details/scan-passport-chip.tsx, apps/docs/src/common/pages/patterns/enter-passport-details/take-upload-photo.tsx
Make links absolute as differences in production led to broken links.
Fix Issue 551 (https://github.com/UKHomeOffice/design-system/issues/511) with broken links on the passport details page.
=> Fix links on enter passport details

apps/docs/src/common/pages/content-style-guide.tsx
Removed 'or emails' from:
postal
Use 'postal address' rather than 'correspondence' if you mean letters or emails. For example, 'is this the family's postal address?'
Added 'address' to 'email':
correspondence
Correspondence is not plain English. Try to be specific such as ‘postal address’, ‘contact address’ or ‘email address’. For example, ‘is this the family’s postal address?’
=> Removed 'emails' from 'postal'

apps/docs/src/common/pages/content-style-guide.tsx
New to the guide:
British citizen
British citizen is one of 6 different types of British nationality. Do not use ‘UK citizen’.
British nationality
There are 6 different types of British nationality. These are British citizen, British overseas territories citizen, British overseas citizen, British subject, British national (overseas) and British protected person.
Naturalisation
Naturalisation is a legal process someone goes through to become a British citizen. For example, ‘apply for a certificate of naturalisation’.
As a follow onto https://github.com/UKHomeOffice/design-system/pull/534
=> 3 new entries: citizen, nationality and naturalisation

.github/actions/setup/action.yml, .github/workflows/change-assurance.yml, pnpm-lock.yaml
**BREAKING:** Drops support for Node.js v14.
=> CI: Update PNPM

apps/docs/src/common/pages/get-started/start-prototype.tsx
Remove node version 14 from the instructions.
=> Update instructions to use node 18 or 16

apps/docs/src/common/pages/content-style-guide.tsx
New entries added:
Added under 'Biometric passport' and 'ePassport':
Use ‘passport’ if the type of passport does not matter. When referring to passports with a chip, use ‘biometric passport’ instead of ‘ePassport’.
eGates
When using ‘eGates’ with the public, explain what it means the first time you use it. For example, ‘you will have the option of using an eGate (electronic passport gate)’.
=> eGates and ePassport

apps/docs/src/common/pages/content-style-guide.tsx
New entries:
asylum claimant and refugee
=> Asylum claimant and refugee

apps/docs/src/common/pages/content-style-guide.tsx
Contractions
Avoid negative contractions like ‘don’t’. See guidance on contractions in the http://GOV.UK style guide.
Avoid all contractions, including positive contractions like ‘we’ll', 'you’ve' or 'they’re', if your audience does not speak English as a first language. Research shows that contractions make content difficult to understand for people who are not fluent in English.
=> Updated  'contractions'

.github/actions/test-code/action.yml, .github/workflows/change-assurance.yml
With the current version of the action, we must avoid overriding artefacts in matrix builds.
=> CI: Fix artefact uploads

apps/docs/src/common/pages/content-style-guide.tsx
UK Visas and Immigration (UKVI)
Capitalised. Use 'and' not '&'. You can use the acronym ‘UKVI’ after the first full mention.
=> New UKVI guidance

components/status-message/assets/StatusMessage.scss
Fixes an issue in which buttons could overflow on narrow screens when multiple buttons were used.
See: https://github.com/UKHomeOffice/design-system/discussions/419#discussioncomment-8112422
closes: #572
=> StatusMessage: Re-use button-group SCSS

apps/docs/src/common/pages/styles/colour.tsx
#531 raises that the background colour of the Home Office Design System is different to the one on the 'Colour' page of the design system.
This fixes this issue and updates the colour page to #f5f5f5
=> Update description of background colour

README.md
"Install pnpm" link in the readme "Getting Started" section was broken because pnpm site has switched domains. I've replaced the link with correct one.
Fixes #569.
Thank you.
=> Fix broken install pnpm link in README

.github/actions/scan-app/action.yml
Good afternoon.
"Scan service for vulnerabilities" workflow was failing because `owasp/zap2docker` Docker image does not exist any longer, it has been deprecated and replaced with `owasp/zaproxy` image with following error:
```
Error response from daemon: pull access denied for owasp/zap2docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
I have upgraded two actions in this workflow:
- zaproxy/action-baseline (v0.4.0 -> v0.10.0)
- zaproxy/action-full-scan (v0.7.0 -> v0.12.0)
This should fix the failing scan. 
Thank you.
=> Fix: Failing Build on scan-app Action

apps/docs/src/common/pages/accessibility/inclusive-language.tsx, apps/docs/src/common/pages/content-style-guide.tsx, apps/docs/src/common/pages/contribute.tsx, apps/docs/src/common/pages/contribute/design-system-working-group.tsx, apps/docs/src/common/pages/get-started.tsx, apps/docs/src/common/pages/styles/colour.tsx, apps/docs/src/common/pages/styles/images.tsx, docs/accessibility-statement.md
Our e-mail address has changed. We should also think about when and where we want to provide an email address and when we want to direct people only to a GitHub discussion.
An alternative to: #581
=> Update contact email address

apps/docs/src/common/pages/get-started/home-office-plugin.tsx
Small update to HO plugin installation instructions. See issue https://github.com/UKHomeOffice/design-system/issues/604
=> Update plugin instructions

.npm/version.sh
We don't want to commit the package lock-file itself anymore. Instead we should commit a substitute, as we do elsewhere.
=> CI: Commit correct file in version script

apps/docs/src/common/pages/content-style-guide/designing-for-limited-english.tsx
New copy added: 
<p>Research with vulnerable users for the Home Office's <A href="https://www.gov.uk/guidance/online-immigration-status-evisa">eVisas</A> project revealed that most participants, including fluent English speakers, found the written guidance too long and technical. They said the information in the <A href="https://www.youtube.com/watch?v=54rPXUHuM3I">What is an eVisa?</A> video was easier to understand.</p>
=> New paragraph added to Images and Videos section

components/service-navigation/assets/ServiceNavigation.scss, components/ucdm-header/assets/Header.scss, components/ucdm-page/assets/Page.scss, components/ucdm-section/assets/Section.scss
Styling design tweaks using KISS principles to reduce visual noise and simplify the user interface.
-
Changes have a dependency on removing duplicate section header item in secondary navigation and removing page banner which is currently separating the primary and secondary navigation too much.
-
PR changes as follows:
* Remove multiple horizontal borders from service navigation to reduce overall number of horizontal lines
* Add bold font weight to active item on sub-navigation to make it more intuitive to see which item is currently active
* Increase right margin on header to give logo more space
* Use horizontal line only once (in brand colour) to separate primary and secondary navigation, leaving spacing and page background colour to create visual divisions of primary, secondary …
=> UCDM design tweaks
