UKHomeOffice/design-system

app/views/index.html
app/views/process/contribute.html
app/views/process/guidance.html

Amended links on homepage to point to new copy

Updated contribution and guidance copy.

---

app/views/flash-card.html
app/views/header.html
app/views/icons.html

Implemented all changes from earlier review of patterns in ‘beta’.

Content updated for beta patterns

---

app/views/components/badges.html
app/views/components/buttons.html
app/views/components/cards.html
app/views/components/checkboxes.html
app/views/components/icons.html
app/views/components/labels.html
app/views/components/radios.html
app/views/components/typography.html
app/views/patterns/confirm-pages.html
app/views/patterns/flash-card.html
app/views/patterns/header.html
app/views/patterns/help.html
app/views/patterns/highlighting-matches.html
app/views/patterns/modal.html
app/views/patterns/navigation.html
app/views/patterns/table-multiselect.html
app/views/patterns/tabs.html
app/views/patterns/tasks.html
app/views/patterns/timeline.html

Updated all component and pattern pages to be consistent with h1, lede, removed old banner header sections.
Tidied up the grid structures too.

Header removal tdy

---

app/assets/sass/application.scss
app/assets/sass/patterns/_help.scss
app/views/includes/patterns/help.html
app/views/patterns/help.html

I've coded this up but it's rough so needs tidying up. Also I can show the help overlay but not hide it again at the moment.

dev: help overlay coded up

---

app/assets/sass/components/_buttons.scss
app/assets/sass/patterns/_header.scss
app/views/components/buttons.html
app/views/includes/components/button-primary-alt.html
app/views/includes/components/buttons-secondary.html
app/views/includes/components/buttons.html

Updating of button component to add definition and clarity from more user research.
**Changes to the component**
- secondary button changed to be called alternate primary
- secondary button reverted to grey version
- border added to secondary button 
- removed affordance from disabled styling (`box-shadow: none;`)
- updated secondary buttons using icons [experimental]
**Changes to the documentation**
- separated examples out with clarity on use
- updated services using pattern
- updated user research

Update buttons component

---

app/views/components/typography.html

Moved paragraph. Please can you check my work Karwai :-)

dev: move paragraph to make it clear

---

app/views/resources/prototyping.html

I have updated the prototyping.html file (that sits under the resources directory) to add a link to my Balsamiq wireframes as well as adding two new headings for that page.

Added Balsamiq link and new h2 headings.

---

app/views/resources/prototyping.html

Closing tag misplaced causing type display error.

Fix closing tag

---

app/views/index.html

Have updated the homepage with the latest updates to the design system and included the date it was last updated.
Note: Colour of the 'last updated' text - not sure if this is the best way of applying colour to text? I couldn't figure out how to add using the govuk sass variables

latest updates & date added

---

app/views/index.html

Just realised the links in the updates section were broken.

fixed broken links

---

app/views/patterns/guidance-image.html

I have changed the h3s to h2s as requested and also updated the designops@ email in the body to design@. (Will change the email in the contact card in a separate branch)

Guidance images: Updates following accessibility review

---

app/views/community/propose.html

**Before**
If your idea is not on the backlog, raise an issue in Github. Or get in touch with the working group to help you do this.
**After**
If your idea is not on the backlog, raise an issue in Github. You can use our Github guide to help you do this, or get in touch with the working group.

Copy edit on Propose page

---

app/views/getinvolved/backlog.html

Needs accessibility check before pushing to live

adding table to github backlog

---

app/assets/sass/application.scss
app/assets/sass/system/_content.scss
app/views/accessibilitystatement.html
app/views/layout.html
app/views/patterns/find-information-on-a-document.html
app/views/patterns/upload-files.html

@karypun need to check H3 headings as discussed thank you
Need for accessibility and content review

Accessibility statement in HTML

---

app/views/patterns/addresses.html
app/views/patterns/check-and-confirm-details.html
app/views/patterns/find-information-on-a-document.html
app/views/patterns/get-more-details.html
app/views/patterns/make-an-enquiry.html
app/views/patterns/sign-out.html
app/views/patterns/stop-a-service-timing-out.html
app/views/patterns/stop-and-think.html
app/views/patterns/template.html
app/views/patterns/upload-files.html
app/views/styles/index.html

Patterns that have been updated:
- Sign out
- Upload files
- Stop and think
- Addresses
- Check and confirm details
- Get more details
- Stop a service from timing out
- Make an enquiry

Pattern changes: updated content to new template

---

app/views/patterns/access-a-service.html
app/views/patterns/add-multiple-things.html

[- Access a service issue fixed](https://github.com/UKHomeOffice/design-system/issues/180)
[- Add multiple things pattern updated](https://github.com/UKHomeOffice/design-system/issues/179)

Errors in patterns updated

---

app/assets/sass/components/_labels.scss
app/views/getinvolved/backlog.html
app/views/includes/components/highlighting.html
app/views/includes/left-pane__components.html

Highlighted search matches removed from design system and placed into our GitHub backlog

Component removed and added to backlog

---

app/assets/sass/_styles.scss
app/views/styles/colour.html

What's been done:
- New palette added to **primary**, **secondary** and **accessible text & backgrounds** sections

styles - new colours page

---

app/views/accessibilitystatement.html
app/views/styles/colour.html

Update to accessibility statement to reflect the fixes that have been completed

Update accessibility statement

---

app/views/includes/left-pane__resources.html
app/views/index.html
app/views/resources/index.html
app/views/resources/prototyping.html

Added new Figma mapping template in resources 👍

mapping template

---

app/views/index.html
app/views/resources/accessibility.html
app/views/resources/index.html
app/views/resources/prototyping.html
app/views/styles/index.html

Updated link on styles page to point to new cookies guidance and link to revised journey map template. Removed rogue ' in Accessibility page

updates to cookies guidance and journey map template

---

CONTRIBUTING.md
README.md

Some of this content was destroyed in the switch over so let's reinstate
it.

Reinstate content from original README

---

apps/docs/src/common/pages/accessibility/audio-and-video.tsx
apps/docs/src/common/pages/accessibility/colour-and-contrast.tsx
apps/docs/src/common/pages/accessibility/error-messages.tsx
apps/docs/src/common/pages/accessibility/headings.tsx
apps/docs/src/common/pages/accessibility/images.tsx
apps/docs/src/common/pages/accessibility/keyboard.tsx
apps/docs/src/common/pages/accessibility/keyboard/character-key-shortcuts.tsx
apps/docs/src/common/pages/accessibility/keyboard/focus.tsx
apps/docs/src/common/pages/accessibility/keyboard/pointer-gestures.tsx
apps/docs/src/common/pages/accessibility/keyboard/skip-to-content.tsx
apps/docs/src/common/pages/accessibility/keyboard/tab-navigation.tsx
apps/docs/src/common/pages/accessibility/links.tsx
apps/docs/src/common/pages/accessibility/readability.tsx
apps/docs/src/common/pages/accessibility/resources.tsx
apps/docs/src/common/pages/accessibility/tables.tsx
apps/docs/src/common/pages/accessibility/timeouts.tsx

... including examples and resources.

Accessibility tweaks and additions

---

.drone.yml

Update the Drone config from v0.8 to v1.
Thanks go to @aarongill1 and @JamesWoodwardHMPO for [their previous work on this for the LEV project](https://github.com/UKHomeOffice/lev/blob/master/.drone.yml).

Update Drone config

---

components/alert/spec/Alert.stories.mdx

Added content to the alert component page.
Addresses: #391

New content for Alert component page

---

apps/docs/src/common/pages/styles/colour.tsx

This is to make the text sizes consistent.
Addresses: #400

Insert missing paragraph tags

---

components/timeline/src/Timeline.tsx

Fix issue where date and time would be on the same line in timeline page.

Fix timeline issue on same line

---

apps/docs/src/common/pages/accessibility/resources.tsx

Reduced number of accessibility resources to better reflect purpose of the Home Office Design System accessibility section in supporting understanding of the Accessibility Standard.

reduced number of accessibility resources

---

apps/docs/src/common/pages/accessibility/inclusive-language.tsx

Some minor content updates to reflect current thinking.

Content updates to inclusive language guidance.

---

apps/docs/src/common/pages/accessibility/inclusive-language.tsx

Getting this page ready for when posters are uploaded to the HO posters GitHub. Will link to content from 'inclusive language posters.'

Inclusive language page updates + new posters content

---

apps/docs/src/common/pages/accessibility/layout-typography.tsx

changed 300% to 400%

---

apps/docs/package.json
apps/docs/src/common/pages/index.tsx
apps/docs/src/common/pages/patterns.tsx
apps/docs/src/common/pages/patterns/page-blocks.scss
apps/docs/src/common/pages/patterns/send-a-letter.tsx

Following discussion https://github.com/UKHomeOffice/design-system/discussions/377, and resolves issue https://github.com/UKHomeOffice/design-system/issues/458.
Contribute to the discussion for design feedback, and the issue or pull request for development feedback or iterations.

Add letter pattern

---

apps/docs/src/common/pages/content-style-guide.tsx
apps/docs/src/common/pages/contribute.tsx
apps/docs/src/common/pages/contribute/discuss-on-github.tsx
components/alert/spec/Alert.stories.mdx
components/date-display/spec/DateDisplay.stories.mdx
components/date-time/spec/DateTime.stories.mdx
components/expandable-banner/spec/ExpandableBanner.stories.mdx
components/footer/spec/Footer.stories.mdx
components/header/spec/Header.stories.mdx
components/page/spec/Page.stories.mdx
components/pagination/spec/Pagination.stories.mdx
components/status-message/spec/StatusMessage.stories.mdx
components/time/spec/Time.stories.mdx
components/timeline/spec/Timeline.stories.mdx
docs/accessibility-statement.md

Add contribute guidance to the content style guide.
Update contribute guidance to include reference to the content style guide.
Remove broken links to the get-involved page.

Improve contribute guidance to include style guide

---

components/status-message/spec/StatusMessage.stories.mdx

Fixes https://github.com/UKHomeOffice/design-system/issues/462
See discussion: https://github.com/UKHomeOffice/design-system/discussions/419
Following the standard page template: https://github.com/UKHomeOffice/design-system/discussions/430

Add writing for status messages

---

apps/docs/src/common/pages/patterns.tsx
apps/docs/src/common/pages/patterns/access-a-service.tsx
apps/docs/src/common/pages/patterns/add-multiple-things.tsx
apps/docs/src/common/pages/patterns/find-information-on-document.tsx
apps/docs/src/common/pages/patterns/get-more-details.tsx
apps/docs/src/common/pages/patterns/leave-a-service.tsx
apps/docs/src/common/pages/patterns/make-a-declaration.tsx
apps/docs/src/common/pages/patterns/search-for-something.tsx
apps/docs/src/common/pages/patterns/send-a-letter.tsx
apps/docs/src/common/pages/patterns/stop-a-service-timing-out.tsx

- Alphabetise the patterns on the patterns page
- Standardise the content on the patterns pages

Standardise patterns

---

apps/docs/src/common/pages/patterns/compare-information.tsx
apps/docs/src/common/pages/patterns/search-for-something.tsx
components/highlight/.gitignore
components/highlight/README.md
components/highlight/assets/Highlight.scss
components/highlight/jest.config.js
components/highlight/package.json
components/highlight/spec/Highlight.stories.mdx
components/highlight/spec/Highlight.ts
components/highlight/src/Highlight.tsx
components/highlight/tsconfig.json
lib/components/package.json
lib/components/src/index.ts
reports/.sastscan.baseline

- Scaffold files for new Highlight component
- Create component with html & styles as per guidance on ticket #495
- Add Storybook examples and component tests

495 new component highlight

---

apps/docs/src/common/pages/content-style-guide.tsx

British national (overseas)
leave to enter
leave to stay
permission to enter
permission to stay

Edits and new entries to style guide

---

apps/docs/src/common/pages/content-style-guide.tsx

Edit to 'migrants'

---

apps/docs/src/common/pages/content-style-guide.tsx

I've updated the 'people' entry.

'People' updated

---

apps/docs/src/common/pages/content-style-guide.tsx

eVisa
When using ‘eVisa’ in public-facing services, explain what it means. For example, ‘view and prove your online immigration status (eVisa)’.
digital status
Avoid using ‘digital status’ in public-facing services. Instead use ‘eVisa’ or ‘online immigration status’. For example, ‘view and prove your online immigration status (eVisa)’.

New: eVisa and digital status

---

.drone.yml

I'm not sure if this will actually fix it...

CI: Update Node.js in Drone.io

---

apps/docs/src/common/pages/content-style-guide.tsx

Confirm changed to confirm

---

apps/docs/src/common/pages/content-style-guide.tsx

Updated 'passport control' and 'primary control point'.

Updates to primary control point

---

apps/docs/src/common/pages/content-style-guide.tsx

Asylum claimant minor edit

---

apps/docs/src/common/pages/accessibility/inclusive-language.tsx

Find out more about how to ask users for their sex or gender in the Home Office sex and gender pattern.

Added copy and link to sex and gender pattern

---

apps/docs/src/common/pages/content-style-guide.tsx

New entries:
Acronyms
Consignee
Consignor
Contractions
ETA
UAN

Acronyms and other update content-style-guide.tsx

---

apps/docs/src/common/pages/index.tsx

Update last updated section

---

apps/docs/src/common/pages/content-style-guide.tsx

New:
-authorising officer
-sponsor
Updated:
-create, account, register 
-sign in, log in

New and updated guidance

---

apps/docs/src/common/pages/accessibility.tsx
apps/docs/src/common/pages/accessibility/leaders-guide.tsx

Adding Leader’s guide on accessibility to the accessibility section and updating navigation

Adding Leader’s guide on accessibility

---

apps/docs/src/common/pages/content-style-guide.tsx
apps/docs/src/common/pages/content-style-guide/designing-for-limited-english.tsx
apps/docs/src/common/pages/content-style-guide/voice-and-tone.tsx

Attempts to make a few changes to get this working.
If you are happy, it can be merged into your branch before we merge it into the main branch.

Fixes for Voice and Tone PR

---

apps/docs/src/common/pages/content-style-guide/voice-and-tone.tsx

Updates made to voice and tone page after feedback from Style Council.

Content updates to voice and tone

---

apps/docs/src/common/pages/content-style-guide/voice-and-tone.tsx

Updates the GitHub discussion link to go directly to the relevant discussion.

Voice and tone: Link directly to discussion

---

apps/docs/src/common/pages/content-style-guide.tsx

Jan-2025 Update content-style-guide.tsx

---

apps/docs/src/common/pages/design-and-content/content/content-style-guide.tsx

Added new spouse guidance and corrected order so that sorry comes before sponsor guidance.

Spouse update content-style-guide.tsx

---

apps/docs/src/common/pages/index.tsx

Remove 'view more' links as they are inaccessible. Replace with more context around the link that is being clicked.

Remove 'view more' links 

---

docs/community/events/README.md

* Fix markdown title formatting to display as HTML title rather than plain text markdown
* Change reference to accessibility Slack channel to be the main active channel - from 'accessibility' to 'ask-accessibility'

Community page

---

apps/docs/src/common/pages/design-and-content/content/content-style-guide.tsx

New guidance added: 
-phone
-telephone (duplicate of phone guidance)
-mental health

Added phone/telephone and mental health to style guide

---

apps/docs/src/common/pages/design-and-content/content/content-style-guide.tsx

Replaced markdown with full HTML for an unordered list.

Updated phone and telephone entries
